# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

source 'https://cdn.cocoapods.org/'



target 'ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  ###use_frameworks!
  pod 'GooglePlaces','7.2.0'
  pod 'IQKeyboardManagerSwift'
  # Pods for ios

  target 'iosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iosUITests' do
    # Pods for testing
  end

end
